/**
 * This file was generated by the JPA Modeler
 */
package com.kirioslab.heftyfish.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * @author wz
 */
@Entity
@Table(indexes = {
    @Index(name = "EMAIL_INDEX", columnList = "EMAIL", unique = true)})
public class Author implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @NotNull(message = "Author name is undefined.")
    @Size(min = 4, max = 64, message = "Author name lenght shoul be 4 to 64 characters.")
    private String name;

    @Basic
    @NotNull(message = "Author password cannot be null.")
    private String passwordHash;
    
    @Column(unique = true)
    @Basic
    @NotNull(message = "Author email cannot be undefined.")
    @Pattern(regexp = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$",message="Email is not valid.")
    private String email;

    @Column(name = "REGISTRATION_DATE")
    @Basic
    private Timestamp registrationDate;

    @OneToMany(fetch = FetchType.LAZY, targetEntity = BlogPostHeader.class)
    @JoinTable(joinColumns = {
        @JoinColumn(name = "AUTHOR_ID")}, inverseJoinColumns = {
        @JoinColumn(name = "BP_HEADERS_ID")})
    private List<BlogPostHeader> blogPostHeaders;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    
	public String getPasswordHash() {
		return passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Timestamp getRegistrationDate() {
        return this.registrationDate;
    }

    public void setRegistrationDate(Timestamp registrationDate) {
        this.registrationDate = registrationDate;
    }

    public List<BlogPostHeader> getBlogPostHeaders() {
        return this.blogPostHeaders;
    }

    public void setBlogPostHeaders(List<BlogPostHeader> blogPostHeaders) {
        this.blogPostHeaders = blogPostHeaders;
    }
}
