/**
 * This file was generated by the JPA Modeler
 */
package com.kirioslab.heftyfish.jpa;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * @author wz
 */
@Entity
@Table(indexes = {
    @Index(name = "EMAIL_INDEX", columnList = "EMAIL", unique = true)})
public class Author implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @NotNull(message = "Author name is undefined.")
    @Size(min = 4, max = 64, message = "Author name lenght shoul be 4 to 64 characters.")
    private String name;

    @Column(unique = true)
    @Basic
    @NotNull(message = "Author email cannot be undefined.")
    @Pattern(regexp = "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"
     (
    ?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])",message="Email is not valid.")
    private String email;

    @Column(name = "REGISTRATION_DATE")
    @Basic
    private Timestamp registrationDate;

    @OneToMany(fetch = FetchType.LAZY, targetEntity = BlogPostHeader.class)
    @JoinTable(joinColumns = {
        @JoinColumn(name = "AUTHOR_ID")}, inverseJoinColumns = {
        @JoinColumn(name = "BP_HEADERS_ID")})
    private List<BlogPostHeader> blogPostHeaders;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Timestamp getRegistrationDate() {
        return this.registrationDate;
    }

    public void setRegistrationDate(Timestamp registrationDate) {
        this.registrationDate = registrationDate;
    }

    public List<BlogPostHeader> getBlogPostHeaders() {
        return this.blogPostHeaders;
    }

    public void setBlogPostHeaders(List<BlogPostHeader> blogPostHeaders) {
        this.blogPostHeaders = blogPostHeaders;
    }

}
