/**
 * This file was generated by the JPA Modeler
 */
package com.kirioslab.heftyfish.jpa;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author wz
 */
@Entity
@Table(name = "BLOG_POST_HEADER", indexes = {
    @Index(name = "BP_HEADER_INDEX", columnList = "HEADER")})
public class BlogPostHeader implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @NotNull(message = "Blog post header is not defined.")
    @Size(min = 10, max = 255, message = "Blog post header must be 10-255 lenght.")
    private String header;

    @Column(name = "HTML_SHORT_DESCRIPTION", length = 900)
    @Basic
    @NotNull(message = "Blog post description is not defined.")
    @Size(min = 25, max = 900, message = "Blog post description should be 25 to 900 characters lenght.")
    private String htmlShortDescription;

    @Column(name = "PUBLISH_DATE")
    @Basic
    @NotNull
    private Timestamp publishDate;

    @OneToOne(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY, targetEntity = BlogPost.class)
    @JoinColumn(name = "BP_ID")
    private BlogPost blogPost;

    @OneToMany(cascade = {CascadeType.ALL}, fetch = FetchType.LAZY, targetEntity = BlogPostTag.class)
    @JoinTable(name = "HEADER_TAG", joinColumns = {
        @JoinColumn(name = "BLOG_POST_HEADER_ID")}, inverseJoinColumns = {
        @JoinColumn(name = "BLOG_POST_TAGS_ID")})
    private List<BlogPostTag> blogPostTags;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHeader() {
        return this.header;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    public String getHtmlShortDescription() {
        return this.htmlShortDescription;
    }

    public void setHtmlShortDescription(String htmlShortDescription) {
        this.htmlShortDescription = htmlShortDescription;
    }

    public Timestamp getPublishDate() {
        return this.publishDate;
    }

    public void setPublishDate(Timestamp publishDate) {
        this.publishDate = publishDate;
    }

    public BlogPost getBlogPost() {
        return this.blogPost;
    }

    public void setBlogPost(BlogPost blogPost) {
        this.blogPost = blogPost;
    }

    public List<BlogPostTag> getBlogPostTags() {
        return this.blogPostTags;
    }

    public void setBlogPostTags(List<BlogPostTag> blogPostTags) {
        this.blogPostTags = blogPostTags;
    }

}
